#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'


if ARGV.empty?
  puts "Login required!"
  exit
end
login = ARGV[0]
user = User.find_by_login(login)

unless user
  puts "No such user!"
else
  user.update_attribute(:is_admin, true)
  puts "Set admin permissions to #{user.login}"
end

